### ISSUE TITLE
Add tskit standard formatting

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/kastore#104]
Add the standard pre-commit checks for tskit code (Black, etc) here.

**Comment by jeromekelleher** [comment]
@benjeffery, would you mind setting this in motion once #88 is merge please?

**Comment by benjeffery** [comment]
Yep, will do, assign me up!

**Comment by jeromekelleher** [comment]
I think this is the only thing we need to do before tagging C_0.2.

**Comment by jeromekelleher** [comment]
Closed in #111 

Looks like we're good to tag release ``C_2.0.0`` whenever now. Would you like to do the honours @benjeffery? I've used the GitHub releases interface before and just pasted in the CHANGELOG notes, as this seemed simplest.

**Comment by benjeffery** [comment]
@jeromekelleher that PR didn't include clang-format which is on my to-do list, shall we do that beforehand?

**Comment by jeromekelleher** [comment]
Ah yes, let's do that, my bad.
