### ISSUE TITLE
Add github action to automate sdist upload and manylinux wheel builds?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/kastore#110]
Can we use a [GitHub action](https://github.com/marketplace/actions/python-wheels-manylinux-build) to build and upload a manylinux wheel to pypi as part of the release process?

It would be great to do this along with an [automated upoad](https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries) of the sdist that happens after tagging a release.

We can push out a bunch of alpha releases to test and develop this.

@benjeffery, are you up for setting this up?

**Comment by jeromekelleher** [comment]
See also https://github.com/pypa/gh-action-pypi-publish

**Comment by benjeffery** [comment]
Yep, already looked into this, packages like msgpack do this exact thing. I'll self-assign.

**Comment by benjeffery** [comment]
@jeromekelleher I don't think I have permission to self-assign

**Comment by jeromekelleher** [comment]
Should have admin access now. We also need to set you up with a PyPI account/access to tskit-dev. Do you have a pypi account setup?

**Comment by jeromekelleher** [comment]
Looks like I just need your PyPI username and I can add you to the various projects.

**Comment by jeromekelleher** [comment]
One thing to watch out for: we have separate tagging for C and Python releases (#73). We'll need to make sure we don't trigger a Python release upload if the tag starts with "C_" I guess.
