### ISSUE TITLE
Circle builds failing on master

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/kastore#119]
Not sure why

**Comment by jeromekelleher** [comment]
Some stuff about kastore not having any workflows enabled, and a circular rabbithole of configuration options. Not sure what's going on here, possible something to do with the new UI.

**Comment by benjeffery** [comment]
Will look into it

**Comment by benjeffery** [comment]
Regenerating the Circle CI deploy key seems to have fixed this.
