### ISSUE TITLE
oldest-supported-numpy needs to go into wheel building

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/kastore#129]
In #127 I removed the reference to ``oldest-supported-numpy`` from setup.py as I thought that this was an extra check not related to the wheel building process. But I think this is actually how the wheel building process was fixing the numpy version. (I thought from earlier incarnations there was a requirements.txt for this).

We should be able to install ``oldest-supported-numpy`` at the same time as we ``pip install setuptools wheel``, right?

**Comment by jeromekelleher** [comment]
Confirming that we're not building the wheels against a new version of numpy. Here's the relevant include paths from the latest push:
```
 -I/opt/python/cp37-cp37m/include/python3.7m -I/project/python/.eggs/numpy-1.18.4-py3.7-linux-x86_64.egg/numpy/core/include
```
whereas for the released version we have 
```
 -I/opt/python/cp37-cp37m/include/python3.7m -I/project/python/.eggs/numpy-1.14.5-py3.7-linux-x86_64.egg/numpy/core/include
```

**Comment by benjeffery** [comment]
An earlier version did have a requirements file for wheel building - which was removed as I realised the correct way to specify build deps is in `setup.py` 
Maybe it is possible to detect conda and conditionally use `oldest-supported-numpy`? I'll look into it.

**Comment by jeromekelleher** [comment]
> An earlier version did have a requirements file for wheel building - which was removed as I realised the correct way to specify build deps is in setup.py

Why is it correct to specify it in setup.py? I think the environment should choose which version of numpy you're building against - if you're just building a package for your own system, then you use your own version of numpy. If you're building binary wheels for distribution, you install the appropriate version of numpy in that environment. If you're building for conda, conda-forge sets up the environment. If you're building for easy-build, they set the environment where the wheel is built.
