### ISSUE TITLE
C API installation ?

### ISSUE THREAD

**Issue by Becheler** [tskit-dev/kastore#133]
Hi !
I would like to install the C API, but the documentation seems to indicate it's a TODO feature :)
I can find a workaround copy/pasting files and using CMake, but if there was a more recommanded/stable solution that would be awesome :)
Thank you !

**Comment by jeromekelleher** [comment]
Hi @Becheler, great to see you're interested in kastore!

I think this should work, it's just not something we're documenting or recommending for normal users. If you have a recent version of [meson](https://mesonbuild.com/) running ``meson install`` should do the trick. There's more info [here](https://mesonbuild.com/Installing.html).

We're also testing it out during CI [here](https://github.com/tskit-dev/kastore/blob/0dcfc60297560f218b074e9dd9d105780f01ea61/.circleci/config.yml#L91)

This should be long-term stable.

**Comment by benjeffery** [comment]
I'm assuming this is ready to close, please re-open if you need.
