### ISSUE TITLE
trivial fix needed for warning

### ISSUE THREAD

**Issue by bhaller** [tskit-dev/kastore#142]
I'm not good at doing pull requests, so I'll leave this here.  :->  In kastore.c, there is this code (starting line 732):

```
static int KAS_WARN_UNUSED
kastore_gets_type(
    kastore_t *self, const char *key, void **array, size_t *array_len, int type)
{
    int loaded_type;
    int ret;

    ret = kastore_get(self, key, strlen(key), array, array_len, &loaded_type);
    if (ret != 0) {
        goto out;
    }
    if (type != loaded_type) {
        ret = KAS_ERR_TYPE_MISMATCH;
        goto out;
    }
out:
    return ret;
}
```

Dumb compilers, such as the one on Cornell's cluster (gcc 4.8.5), don't understand that `loaded_type` is not used uninitialized at the point of `if (type != loaded_type)`, and so they issue a warning, once for every time `kastore_gets_type()` is used, which is a bunch of times (depending on warning settings, no doubt; SLiM uses rather aggressive warning settings for its build).  To reassure such compilers, it'd be nice to just do `int loaded_type = 0;` at line 736.  Smart compilers will probably optimize the assignment away, so there might not even be any overhead.  :->

**Comment by molpopgen** [comment]
Is this triggered by -W -Wall, or is something more strict needed?

Kinda amazing that that compiler can still be found anywhere!

**Comment by bhaller** [comment]
> Is this triggered by -W -Wall, or is something more strict needed?

The warning flags SLiM uses for CMake builds right now are:

-Wno-attributes -Wunused-label -Wimplicit -Wunused-variable -Wunused-value -Wno-pragmas -Wempty-body -Wshadow -Wparentheses -Wmissing-prototypes -Wswitch -Wpointer-sign -Wsign-compare -Wstrict-prototypes -Wno-sign-conversion -Wuninitialized

Presumably -Wuninitialized is what triggers this, but I haven't experimented.  It's the only warning I see with that compiler on the Cornell cluster, building SLiM.

> Kinda amazing that that compiler can still be found anywhere!

Yeah; lots of cluster admins hesitate to upgrade anything for fear of breaking things, I guess.  It is literally the oldest compiler I support, because it's the first version of GCC that has sufficient support for C++11, I think.

**Comment by jeromekelleher** [comment]
Thanks for the report @bhaller, fixed now. Would you like us to tag a release to include this in the C API? Otherwise the fix won't show up downstream for a good while.

**Comment by petrelharp** [comment]
We can merge it in to SLiM even without a release if we want...

**Comment by bhaller** [comment]
Thanks @jeromekelleher and @petrelharp.  Yes, I made the change in SLiM's copy of the kastore code already, just to squash the warning.  So there's no need for any sort of accelerated roll-out.  Next time @petrelharp merges from tskit into SLiM, that will just overwrite the temporary fix I did.  Thanks!

**Comment by jeromekelleher** [comment]
OK, sounds good @bhaller. Not worth doing a release for this, so good you have a workaround till we package one up.

**Comment by bhaller** [comment]
> OK, sounds good @bhaller. Not worth doing a release for this, so good you have a workaround till we package one up.

Yep; and in any case it's just a warning, not the end of the world.  :->
