### ISSUE TITLE
Ship standalone C tarball

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/kastore#159]
Not having an artefact that we can refer to as the standalone C dependency is making using kastore (and tskit) very tricky to use in the C context. In particular, it's making it very hard to use meson subprojects, and we're are currently having to pin to an older version of meson to make our builds work at the moment.

Using git submodule sort-of works, but we can't just check out the ``c`` directory on its own. As a result we currently have a vipers nest of soft-links which has lots of other drawbacks.

What we want ideally is a tarball that contains just the ``c`` directory,  so ``kastore-0.2.1.tar.gz``, and looks like
```
CHANGELOG.rst
kastore.c
kastore.h
meson.build
.... etc
```

Maybe we could use something like [this](https://github.com/softprops/action-gh-release) to create this tarball and store the sha256 sum somewhere? Would it show up in the GitHub release assets? Where could we store it?

Any thoughts @benjeffery?

**Comment by benjeffery** [comment]
Yep, sounds like a great idea. We can have a tarball that is attached to github releases and stored by github, that repo you linked to has all the functionality we need to do this.

**Comment by jeromekelleher** [comment]
I think this would really simplify our meson build setup - we can create meson [wrap files](https://mesonbuild.com/Wrap-dependency-system-manual.html) that point to the tarball and meson will then fetch and unpack the tarball automatically.

It'd be extra nice if we could compute the sha256 sum and display it somewhere, but that's just icing really.

**Comment by jeromekelleher** [comment]
Would you like to have a go at it @benjeffery  - nice to have it for the 2.0.1 release that's ready to drop.

**Comment by benjeffery** [comment]
Yep should be straight forward.

**Comment by jeromekelleher** [comment]
Any progress on this @benjeffery? It'd be nice to get the kastore C release out, so we can get the cascade started at least :smile:

**Comment by benjeffery** [comment]
That tool doesn't create zipfiles :( I looked around and it would mean making a custom action. It is a simple enough task to do manually that it doesn't justify the dev work for now. See https://github.com/tskit-dev/kastore/releases/download/C_2.0.1/kastore-0.2.1.tar.gz

**Comment by jeromekelleher** [comment]
> That tool doesn't create zipfiles 

Do we want zipfiles (as opposed to tarballs)? What's the blocker, the action won't let you make your own distribution assets or you can't upload them?

But yeah, posting the tarball using the github interface at the same time as creating the release (I assume this is what you did?) isn't so bad. We'd probably want *some* tooling though, so that the tarballs we're creating are uniform, and I guess we should document the process also?

I think we should do this for the upcoming tskit C releases, which is why I'm pushing on this now.

**Comment by benjeffery** [comment]
That action only lets you upload, not create assets. Sorry was using "zipfile"  to mean a `.tar.gz`.
If we are using this across tskit-dev then it might be worth coding up an action.

**Comment by jeromekelleher** [comment]
> That action only lets you upload, not create assets. 

Ah right, bummer.

> If we are using this across tskit-dev then it might be worth coding up an action.

Just here and tskit I think - that's the only place we're shipping C artifacts, right?

**Comment by jeromekelleher** [comment]
I'm reopening this - I think it's worth making this automatic. As #169 and #170 show it's very easy to make mistakes doing this stuff manually.

**Comment by jeromekelleher** [comment]
I've updated the tarball for 2.0.1, using the following procedure:
```
mkdir kastore-2.0.1
cp -R c/* kastore-2.0.1
tar -cvhf kastore-2.0.1.tar.gz kastore-2.0.1/
sha256sum kastore-2.0.1.tar.gz
```

**Comment by jeromekelleher** [comment]
Might be worth trying to get [meson dist](https://mesonbuild.com/Creating-releases.html) to build here. This will probably involve setting the version number in the meson.build (but maybe that's not so bad?).

**Comment by benjeffery** [comment]
I have `meson dist` working, except for the symlink resolution which I'm looking into.

**Comment by benjeffery** [comment]
Doing some testing as using the action creates a release - this is normally how we manually trigger a pypi upload after checking the test pypi, so seeing if a draft release can be created and then published to trigger pypi.
