### ISSUE TITLE
error code not returned

### ISSUE THREAD

**Issue by bhaller** [tskit-dev/kastore#160]
This one is thanks to Xcode's static analyzer.  In `kastore_open()` there is a spot where an error code is stored but never read:

        if (err != 0) {
            ret = KAS_ERR_IO;
        }

This is at kastore.c:560.  It looks to me like you're missing a `goto out;` there.

**Comment by jeromekelleher** [comment]
Well spotted Xcode, and thanks for the report @bhaller!
